# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0005_inpatient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpatient',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inpatient',
            name='starting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
